spring:
  jpa:    
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: true
    
  datasource:
    url: jdbc:mysql://localhost:3306/delfosapi?characterEncoding=UTF-8&useLegacyDatetimeCode=true&createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
    password: 1234
    
  jackson:
    deserialization:
      fail-on-unknown-properties: true
      
  profiles:
    active: oauth-security
    group:
      prod: oauth-security
    
api:
  version: v1
  via:
    cep: https://viacep.com.br/ws/
    
    
#delfos:
#  seguranca:
#    redirects-permitidos: http://local-delfos.com:8000/authorized, https://oidcdebugger.com/debug
#    auth-server-url: http://localhost:8080
#  origin-permitida: http://local-delfos.com:8000